import {Component, EventEmitter, Input, OnInit, Output} from '@angular/core';
import {AbstractControl, FormBuilder, FormControl, FormGroup, Validators} from '@angular/forms';
import {log} from 'util';


@Component({
  selector: 'app-edit-form',
  templateUrl: './edit-form.component.html',
  styleUrls: ['./edit-form.component.css']
})
export class EditFormComponent implements OnInit {

  @Input()
  editingUser;
  @Output()
  bubbleUp = new EventEmitter();

  editUserForm: FormGroup;

  constructor(private formBuilder: FormBuilder) {
  }

  ngOnInit(): void {
    this.initForm();
  }

  closeForm(): void {
    this.bubbleUp.emit('close');
  }

  private initForm(): void {
    this.editUserForm = this.formBuilder.group({
      name: new FormControl(this.editingUser.name, [Validators.required, this.minLength]),
      username: this.editingUser.username,
      email: this.editingUser.email,
      street: this.editingUser.address.street,
      suite: this.editingUser.address.suite,
      city: this.editingUser.address.city,
      zipcode: this.editingUser.address.zipcode,
      lat: this.editingUser.address.geo.lat,
      lng: this.editingUser.address.geo.lng,
      phone: this.editingUser.phone,
      website: this.editingUser.website,
      companyName: this.editingUser.company.name,
      catchPhrase: this.editingUser.company.catchPhrase,
      bs: this.editingUser.company.bs,
    });
  }

  saveForm(editUserForm): void {
    if (editUserForm.status === 'VALID') {
      const {
        name, username, email, street, suite, city, zipcode, lat, lng, phone, website, companyName, catchPhrase, bs
      } = this.editUserForm.value;

      const editedUser = {
        id: this.editingUser.id,
        name, username, email, phone, website,
        address: {
          street, suite, city, zipcode,
          geo: {lat, lng}
        },
        company: {name: companyName, catchPhrase, bs}
      };

      this.bubbleUp.emit(editedUser);
    }
  }


  // V A L I D A T O R S //
  minLength(inputData: AbstractControl): any {
    const arrBadWords = [
      'архипиздрит',
      'басран',
      'бздение',
      'бздеть',
      'бздех',
      'бзднуть',
      'бздун',
      'бздунья',
      'бздюха',
      'бикса',
      'блежник',
      'блудилище',
      'бляд',
      'блябу',
      'блябуду',
      'блядун',
      'блядунья',
      'блядь',
      'блядюга',
      'взьебка',
      'волосянка',
      'взьебывать',
      'выблядок',
      'выблядыш',
      'выебать',
      'выеть',
      'выпердеть',
      'высраться',
      'выссаться',
      'говенка',
      'говенный',
      'говешка',
      'говназия',
      'говнецо',
      'говно',
      'говноед',
      'говночист',
      'говнюк',
      'говнюха',
      'говнядина',
      'говняк',
      'говняный',
      'говнять',
      'гондон',
      'дермо',
      'долбоеб',
      'дрисня',
      'дрист',
      'дристать',
      'дристануть',
      'дристун',
      'дристуха',
      'дрочена',
      'дрочила',
      'дрочилка',
      'дрочить',
      'дрочка',
      'ебало',
      'ебальник',
      'ебануть',
      'ебаный',
      'ебарь',
      'ебатория',
      'ебать',
      'ебаться',
      'ебец',
      'ебливый',
      'ебля',
      'ебнуть',
      'ебнуться',
      'ебня',
      'ебун',
      'елда',
      'елдак',
      'елдачить',
      'заговнять',
      'задристать',
      'задрока',
      'заеба',
      'заебанец',
      'заебать',
      'заебаться',
      'заебываться',
      'заеть',
      'залупа',
      'залупаться',
      'залупить',
      'залупиться',
      'замудохаться',
      'засерун',
      'засеря',
      'засерать',
      'засирать',
      'засранец',
      'засрун',
      'захуячить',
      'злоебучий',
      'изговнять',
      'изговняться',
      'кляпыжиться',
      'курва',
      'курвенок',
      'курвин',
      'курвяжник',
      'курвяжница',
      'курвяжный',
      'манда',
      'мандавошка',
      'мандей',
      'мандеть',
      'мандища',
      'мандюк',
      'минет',
      'минетчик',
      'минетчица',
      'мокрохвостка',
      'мокрощелка',
      'мудак',
      'муде',
      'мудеть',
      'мудила',
      'мудистый',
      'мудня',
      'мудоеб',
      'мудозвон',
      'муйня',
      'набздеть',
      'наговнять',
      'надристать',
      'надрочить',
      'наебать',
      'наебнуться',
      'наебывать',
      'нассать',
      'нахезать',
      'нахуйник',
      'насцать',
      'обдристаться',
      'обдристаться',
      'обосранец',
      'обосрать',
      'обосцать',
      'обосцаться',
      'обсирать',
      'опизде',
      'отпиздячить',
      'отпороть',
      'отъеть',
      'охуевательский',
      'охуевать',
      'охуевающий',
      'охуеть',
      'охуительный',
      'охуячивать',
      'охуячить',
      'педрик',
      'пердеж',
      'пердение',
      'пердеть',
      'пердильник',
      'перднуть',
      'пердун',
      'пердунец',
      'пердунина',
      'пердунья',
      'пердуха',
      'пердь',
      'передок',
      'пернуть',
      'пидор',
      'пизда',
      'пиздануть',
      'пизденка',
      'пиздеть',
      'пиздить',
      'пиздища',
      'пиздобратия',
      'пиздоватый',
      'пиздорванец',
      'пиздорванка',
      'пиздострадатель',
      'пиздун',
      'пиздюга',
      'пиздюк',
      'пиздячить',
      'писять',
      'питишка',
      'плеха',
      'подговнять',
      'подъебнуться',
      'поебать',
      'поеть',
      'попысать',
      'посрать',
      'поставить',
      'поцоватый',
      'презерватив',
      'проблядь',
      'проебать',
      'промандеть',
      'промудеть',
      'пропиздеть',
      'пропиздячить',
      'пысать',
      'разъеба',
      'разъебай',
      'распиздай',
      'распиздеться',
      'распиздяй',
      'распроеть',
      'растыка',
      'сговнять',
      'секель',
      'серун',
      'серька',
      'сика',
      'сикать',
      'сикель',
      'сирать',
      'сирывать',
      'скурвиться',
      'скуреха',
      'скурея',
      'скуряга',
      'скуряжничать',
      'спиздить',
      'срака',
      'сраный',
      'сранье',
      'срать',
      'срун',
      'ссака',
      'ссаки',
      'ссать',
      'старпер',
      'струк',
      'суходрочка',
      'сцавинье',
      'сцака',
      'сцаки',
      'сцание',
      'сцать',
      'сциха',
      'сцуль',
      'сцыха',
      'сыкун',
      'титечка',
      'титечный',
      'титка',
      'титочка',
      'титька',
      'трипер',
      'триппер',
      'уеть',
      'усраться',
      'усцаться',
      'фик',
      'фуй',
      'хезать',
      'хер',
      'херня',
      'херовина',
      'херовый',
      'хитрожопый',
      'хлюха',
      'хуевина',
      'хуевый',
      'хуек',
      'хуепромышленник',
      'хуерик',
      'хуесос',
      'хуище',
      'хуй',
      'хуйня',
      'хуйрик',
      'хуякать',
      'хуякнуть',
      'целка',
      'шлюха',
    ];
    let error = null;

    arrBadWords.map(item => {
      console.log(inputData.value.includes(item));
      if (inputData.value.includes(item)) {
        error = {error: true, msg: `${item} is present`};
      }
    });
    return error;
  }
}
